server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: XXXX
#    url: jdbc:mysql://localhost:3306/accreditation
    url: jdbc:mysql://XXXXX:3306/accreditation


  webflux:
    hidden-method:
      filter:
        enabled: true
  thymeleaf:
    cache:false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB